_wandb:
    value:
        cli_version: 0.23.1
        e:
            b0xr9unfh896vlizlzx2b86k5dd17bx9:
                email: s224022@dtu.dk
                executable: /Users/mortenkleist/miniconda3/envs/my_environment/bin/python
                git:
                    commit: 3d87f3573607789516457cddebf925547c450cfb
                    remote: https://github.com/MortenKleist/CorruptedMNIST.git
                host: MacBook-Pro-tilhrende-Morten-2.local
                os: macOS-15.1.1-arm64-arm-64bit
                program: -m corrupted_mnist.train
                python: CPython 3.11.14
                root: /Users/mortenkleist/Documents/DTU/CorruptedMNIST/CorruptedMNIST/src
                startedAt: "2026-01-08T12:52:26.919098Z"
                writerId: b0xr9unfh896vlizlzx2b86k5dd17bx9
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 2
                - 16
            "4": 3.11.14
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
batch_size:
    value: 32
epochs:
    value: 10
learning_rate:
    value: 0.001
